Repository flyve-mdm/android-mdm-agent, pull requests merged in 2018-08, with the labels that each got.

#533 Install fastlane on deploy
  .circleci/config.yml
Labels: ci

#534 Manage android application bundle with fastlane
  fastlane/Fastfile
Labels: ci

#536 Add version code and version name on the workflow
  .circleci/config.yml
Labels: ci

#540 Update the version code
  app/src/main/AndroidManifest.xml
Labels: ci

#544 Remove parameters for version name
  .circleci/config.yml
  app/src/main/AndroidManifest.xml
Labels: ci

#555 Update compatibility matrix
  README.md
Labels: documentation

#556 Increase the version code
  app/src/main/AndroidManifest.xml
Labels: build

#558 Add new debug logs
  app/src/main/java/org/flyve/mdm/agent/core/enrollment/EnrollmentHelper.java
  app/src/main/java/org/flyve/mdm/agent/ui/MDMAgent.java
  app/src/main/java/org/flyve/mdm/agent/utils/ConnectionHTTP.java
Labels: feature
