Repository flyve-mdm/android-mdm-agent, pull requests merged in 2018-04, with the labels that each got.

#333 Update app status just if the package is installed
  app/src/main/java/org/flyve/mdm/agent/ui/InstallAppActivity.java
Labels: bug

#355 Validate adapters
  app/src/main/java/org/flyve/mdm/agent/adapter/ApplicationsAdapter.java
  app/src/main/java/org/flyve/mdm/agent/adapter/ConnectivityAdapter.java
  app/src/main/java/org/flyve/mdm/agent/adapter/DrawerAdapter.java
  app/src/main/java/org/flyve/mdm/agent/adapter/FilesAdapter.java
  app/src/main/java/org/flyve/mdm/agent/adapter/LogAdapter.java
  app/src/main/java/org/flyve/mdm/agent/adapter/PoliciesAdapter.java
Labels: bug

#360 Open password intent from notification
  app/src/main/java/org/flyve/mdm/agent/ui/MainActivity.java
Labels: feature

#361 Improve download file progress
  app/src/main/java/org/flyve/mdm/agent/services/PoliciesFiles.java
  app/src/main/java/org/flyve/mdm/agent/ui/FragmentTestPolicies.java
  app/src/main/java/org/flyve/mdm/agent/utils/ConnectionHTTP.java
Labels: bug

#363 Improve error message on error screen
  app/src/main/java/org/flyve/mdm/agent/services/MQTTService.java
Labels: feature

#370 add Czech Republic language
  .tx/config
Labels: feature

#374 Add matrix of policies and API level
  _posts/static/2017-12-26-getting-started.md
  _posts/static/2018-04-22-policies.md
Labels: documentation

#377 Fix the problem with Transifex
  .tx/config
Labels: ci

#380 Improve style of policy matrix
  _posts/static/2018-04-22-policies.md
  _sass/_general.scss
Labels: documentation

#378 Add agent compatibility matrix
  README.md
Labels: documentation

#397 Update version code
  app/src/main/AndroidManifest.xml
Labels: ci

#395 Fix handling of deeplink and qr code
  app/src/main/java/org/flyve/mdm/agent/ui/StartEnrollmentActivity.java
Labels: bug

#398 Remove update version script
  .circleci/config.yml
Labels: ci

#387 Update inventory library 0.7.0
  app/build.gradle
Labels: bug, build

#402 Upgrade inventory library 0.7.1
  app/build.gradle
Labels: feature
