Repository flyve-mdm/android-mdm-agent, pull requests merged in 2018-05, with the labels that each got.

#421 Check android api version on status bar
  app/src/main/java/org/flyve/mdm/agent/services/PoliciesDeviceManager.java
Labels: bug

#427 Fix inventory on MQTT connect
  app/src/main/java/org/flyve/mdm/agent/services/MQTTService.java
Labels: bug, refactor

#438 Remove badge of deleted telegram group
  README.md
Labels: documentation

#439 Add professional services to Readme
  README.md
Labels: documentation

#447 Update libraries
  app/build.gradle
Labels: build

#451 Refactor call policies
  app/src/main/java/org/flyve/mdm/agent/services/MQTTService.java
Labels: refactor

#452 Add spanish argentina language
  .tx/config
Labels: ci

#460 Add beta testing app link
  README.md
Labels: documentation

#461 Add beta testing app link
  _posts/static/2017-12-21-installation.md
Labels: documentation
