Repository flyve-mdm/android-mdm-agent, pull requests merged in 2018-09, with the labels that each got.

#563 Add GPG steps
  _posts/static/2017-12-21-how-to-contribute.md
Labels: documentation

#564 Improve the application status
  app/src/main/java/org/flyve/mdm/agent/adapter/ApplicationsAdapter.java
Labels: bug

#570 Remove download progress notification
  app/src/main/java/org/flyve/mdm/agent/services/PoliciesFiles.java
Labels: bug

#576 Update Gemfile.lock
  Gemfile.lock
Labels: bug

#592 Add path to folder for documentation
  ci/scripts/generate_documentation.sh
Labels: ci, documentation

#594 Dropdown for coverage and test report
  _includes/header.html
  development/code-documentation/master/index.html
Labels: documentation

#601 Remove deeplink information
  app/src/main/java/org/flyve/mdm/agent/core/enrollment/EnrollmentModel.java
Labels: bug
