Repository flyve-mdm/android-mdm-agent, pull requests merged in 2018-06, with the labels that each got.

#471 Fix payload base64 encode
  app/src/main/java/org/flyve/mdm/agent/utils/Helpers.java
Labels: bug

#480 Update inventory library 0.8.5
  app/build.gradle
Labels: build

#483 Fix CI problem with dynamic apk name on screengrab
  fastlane/Screengrabfile
Labels: ci

#485 Remove connected folder
  _includes/header.html
  development/test-reports/css/base-style.css
  development/test-reports/css/style.css
  development/test-reports/index.html
  development/test-reports/js/report.js
  development/test-reports/org.flyve.inventory.agent.ExampleInstrumentedTest.html
  development/test-reports/org.flyve.inventory.agent.html
  development/test-reports/org.flyve.mdm.agent.SplashTest.html
  development/test-reports/org.flyve.mdm.agent.core.deeplink.DeeplinkModelTest.html
  development/test-reports/org.flyve.mdm.agent.core.deeplink.html
  development/test-reports/org.flyve.mdm.agent.core.enrollment.EnrollmentHelperTest.html
  development/test-reports/org.flyve.mdm.agent.core.enrollment.EnrollmentModelTest.html
  development/test-reports/org.flyve.mdm.agent.core.enrollment.html
  development/test-reports/org.flyve.mdm.agent.core.permission.PermissionModelTest.html
  development/test-reports/org.flyve.mdm.agent.core.permission.html
  development/test-reports/org.flyve.mdm.agent.core.user.UserModelTest.html
  development/test-reports/org.flyve.mdm.agent.core.user.html
  development/test-reports/org.flyve.mdm.agent.core.walkthrough.WalkthroughModelTest.html
  development/test-reports/org.flyve.mdm.agent.core.walkthrough.html
  development/test-reports/org.flyve.mdm.agent.html
Labels: ci, documentation
