Repository flyve-mdm/android-mdm-agent, pull requests merged in 2018-07, with the labels that each got.

#496 Fix fastlane deploy
  fastlane/Fastfile
Labels: ci

#501 Fix the problem on feedback screen
  app/src/main/java/org/flyve/mdm/agent/ui/FragmentFeedback.java
Labels: bug

#505 Add compatibility matrix
  README.md
Labels: documentation
