Repository flyve-mdm/android-mdm-agent, pull requests merged in 2019-07, with the labels that each got.

#695 Fix build failed for licences not accepted
  .circleci/config.yml
  ci/scripts/ci_licenses.sh
Labels: build, ci

#696 Maintenance commands
  ci/scripts/setup_environment.sh
Labels: build, ci

#694 Better SSL certificate management for MQTT
  app/src/mqtt/java/org/flyve/mdm/agent/core/mqtt/MqttDownloadSSL.java
  app/src/mqtt/java/org/flyve/mdm/agent/core/mqtt/MqttModel.java
Labels: bug, dependent

#702 Update NPM dependencies
  package.json
  yarn.lock
Labels: build

#707 Update fastlane
  Gemfile.lock
Labels: build

#708 Using Bundler 2
  ci/scripts/setup_environment.sh
Labels: build

#710 Setup Ruby Gems Shell script
  .circleci/config.yml
  ci/scripts/setup_ruby_gems.sh
Labels: ci

#711 Remove invalid options for gem install
  ci/scripts/setup_environment.sh
Labels: build
